package daviplata.nacional.iOS.pageObjects;

public class AdsPageObjects {

	public static final String TEXTO_POPUP_ADS = "//XCUIElementTypeStaticText[contains(@name, 'Necesita un adelanto de sueldo')]";
    public static final String BOTON_SABER_MAS = "//XCUIElementTypeStaticText[@name='Saber más']";
    public static final String BOTON_LO_VERE_LUEGO_POPUP_BENEFICIOS_TARJETA_DIGITAL = "";
    public static final String BOTON_TYC_BENEFICIOS = "//XCUIElementTypeTextView[contains(@value, 'Acepto las autorizaciones aquí descritas')]/following-sibling::XCUIElementTypeOther";
    public static final String TXT_BENEFICIOS_CARACTERISTICAS = "//XCUIElementTypeStaticText[@name='Beneficios y Características']";
    public static final String CAMPO_CIUDAD_EXPEDICION_DOCUMENTO = "//XCUIElementTypeTextField[@value='Seleccione una opción']"; 
    public static final String TXT_AUTORIZACIONES = "//XCUIElementTypeStaticText[@name='Autorizaciones']";
    public static final String TXT_RESULTADO = "//XCUIElementTypeStaticText[@name='Resultado']";
    public static final String TXT_AUTORIZADOR_CONTRATO = "//XCUIElementTypeStaticText[contains(@name, 'contrato de mi adelanto de sueldo')]";
    public static final String TXT_AUTORIZADOR_DEBITAR = "//XCUIElementTypeStaticText[@name='debitar automáticamente de mi DaviPlata']";
    public static final String TXT_AUTORIZADOR_DEBITAR_AUTOMATICO = "//XCUIElementTypeStaticText[@name='AUTORIZACIÓN DÉBITO AUTOMATICO']"; 
    public static final String TXT_AUTORIZADOR_PAGARE = "//XCUIElementTypeStaticText[contains(@name,'pagaré')]";
    public static final String TXT_AUTORIZADOR_PAGARE_DOCUMENTO = "//XCUIElementTypeStaticText[contains(@name, 'AUTORIZACIÓN PARA DILIGENCIAR EL DOCUMENTO')]";
    public static final String BTN_ACEPTAR = "//XCUIElementTypeStaticText[@name='Aceptar']";
    public static final String BTN_ATRAS = "//XCUIElementTypeImage[@name='Atrás']";
    public static final String BNT_SALIR_APP = "//XCUIElementTypeImage[@name='close']";
    public static final String OPCION_CIUDAD_EXPEDICION = "//XCUIElementTypeOther[contains(@name, 'Cuál es la ciudad de expedición')]/following-sibling::XCUIElementTypeStaticText";
    public static final String BTN_DONE = "//XCUIElementTypeButton[@name='Done']";
    public static final String CAMPO_PAIS_NACIMIENTO = "//XCUIElementTypeTextField[@value='Seleccionar opción']";
    public static final String CAMPO_CIUDAD_NACIMIENTO = "//XCUIElementTypeTextField[@value='Seleccionar opción']"; 
    public static final String OPCION_CIUDAD_NACIMIENTO = "(//XCUIElementTypeImage[@name='Editar'])[3]/following-sibling::XCUIElementTypeStaticText";
    public static final String POP_UP_RETOMAR_SOLICITUD_ADELANTO_SUELDO = ""; 
    public static final String EQUIS_SALIR_APP_ADELANTO_SALDO = "";
    public static final String FORMULARIO_PANTALLA_INFORMACION_PERSONAL = "";
    public static final String BOTON_ATRAS_ADS = ""; 
    public static final String TEXTO_FECHA_EXPEDICION_DOCUMENTO = "";
    public static final String OPCION_COLOMBIA_CIUDAD_NACIMIENTO = "//XCUIElementTypeStaticText[@name='COLOMBIA']";
    public static final String CAMPO_CORREO_ELECTRONICO = "";
    public static final String DESPLEGABLE_DONDE_VIVE = "";
    public static final String CAMPO_DONDE_VIVE = "";
    public static final String OPCION_TIPO_CALLE = "";
    public static final String CAMPO_NUMERO_UNO_DIRECCION = "";
    public static final String CAMPO_NUMERO_DOS_DIRECCION = "";
    public static final String CAMPO_NUMERO_TRES_DIRECCION = "";
    public static final String CHECKOUT_DIRECCION_PRINCIPAL_SI = "";
    public static final String TIPO_INMUEBLE = "";
    public static final String CIUDAD_DONDE_VIVE = "";
    public static final String OPCION_CIUDAD_RESIDENCIA = "";
    public static final String DESPLEGABLE_DONDE_TRABAJA = "";
    public static final String OPCION_TIPO_CALLE_DONDE_TRABAJA = "";
    public static final String CHECKOUT_SI_DIRECCION_PROPIA_DONDE_TRABAJA = "";
    public static final String TIPO_INMUEBLE_DONDE_TRABAJA = "";
    public static final String CIUDAD_DONDE_TRABAJA = "";
    public static final String OPCION_CIUDAD_DONDE_TRABAJA = "";
    public static final String CHECKOUT_NO_INGRESOS_MENSUALES = "";
    public static final String CAMPO_GASTOS_AL_MES = "";
    public static final String CAMPO_SUMA_LO_QUE_TIENE = "";
    public static final String FORMULARIO_PANTALLA_INFORMACION_LABORAL = "";
    public static final String FORMULARIO_PANTALLA_INFORMACION_FINANCIERA = "";
    public static final String SUMA_LO_QUE_DEBE = "";
    public static final String CHECKOUT_NO_PRODUCTOS_MONEDA_EXTRANJERA = "";
    public static final String CHECKOUT_PERSONA_EXPUESTA = "";
    public static final String CHECKOUT_CARGO_POLITICO = "";
    public static final String CHECKOUT_JUNTA_DIRECTIVA = "";
    public static final String CHECKOUT_PERSONA_POLITICAMENTE_EXPUESTA = "";
    public static final String CHECKOUT_FAMILIAR = "";
    public static final String FORMULARIO_PANTALLA_INFORMACION_TRIBUTARIA = "";
    public static final String CHECKOUT_PAIS_RECIDENCIA = "";
    public static final String CHECKOUT_NO_LEY_FACTA = "";
    public static final String CHECKOUT_SI_LEY_FACTA = "";
    public static final String FORMULARIO_DECLARACIONES = "";
    public static final String NOMBRE_DECLARACION_IMPUESTOS = "";
    public static final String DESPLEGABLE_CLASIFICACION_TRIBUTARIA = "";
    public static final String OPCION_CLASIFICACION_TRIBUTARIA = "";
    public static final String CAMPO_DIRECCION_FACTA = "";
    public static final String CAMPO_CIUDAD = "";
    public static final String CAMPO_CODIGO_POSTAL = "";
    public static final String CAMPO_NUMERO_SEGURO_SOCIAL = "";
    public static final String CHECKOUT_OBJETIVO_ADELANTO = "";
    public static final String CHECKOUT_ORIGEN_RECURSOS = "";
    public static final String CHECKOUT_NO_OBJETIVO_INVESTIGACIONES = "";
    public static final String CHECKOUT_OBJETIVO_AUTORIZACIONES = "";
    
}